### ISSUE TITLE
make regression crashes if config file is missing

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/openlane#85]
With openlane rc4, if the design is missing the config files `make regression` will crash.

```
<prompt>:openlane <user>$ make regression
cd <local_dir> && \
                docker run -it -v <local_dir>:/openLANE_flow -v <local_dir>:<local_dir> -e PDK_ROOT=<pdk_dir> -u 501:20 efabless/openlane:rc4 sh -c "python3 run_designs.py -dts -tar logs reports -html -t TEST_SW_HD -th 4 -p 0"
Traceback (most recent call last):
  File "run_designs.py", line 346, in <module>
    design_name= utils.get_design_name(design, config)
  File "/openLANE_flow/scripts/utils/utils.py", line 55, in get_design_name
    config_file_opener = open(config_file, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/openLANE_flow/./designs/biriscv_tcm//config.tcl'
make: *** [regression] Error 1
```
Maybe change `get_design_name` in `scripts/utils/utils.py` to something like
```
        try:
            config_file_opener = open(config_file, "r")
            configs = config_file_opener.read()
            config_file_opener.close()
        except FileNotFoundError:
            print ("{design} is missing its config file!".format(design=design))
            return "INVALID DESIGN PATH"
```

**Comment by agorararmard** [comment]
@d-m-bailey: Fixed on develop. I'll keep the issue open until it reaches master.
